# stage 1: builder
FROM python:3.12 AS builder

WORKDIR /build
COPY requirements.txt .

RUN pip wheel --no-cache-dir --no-deps -r requirements.txt -w /wheels

# stage 2: export wheels
FROM scratch AS export-wheels
COPY --from=builder /wheels /wheels
